include:
  - traefik/docker-compose.yml
  - postgres/docker-compose.yml
  - vikunja/docker-compose.yml
  - cloudflared/docker-compose.yml
  - immich/docker-compose.yml
  - talkomatic/docker-compose.yml
  - watchtower/docker-compose.yml
  - monitoring/docker-compose.yml
