include:
  - traefik/docker-compose.yml
  - postgres/docker-compose.yml
  - vikunja/docker-compose.yml
  - meals/docker-compose.yml
  - werk/docker-compose.yml
  - talkomatic/docker-compose.yml
  - cloudflared/docker-compose.yml
  - immich/docker-compose.yml
  - watchtower/docker-compose.yml
  - gickup/docker-compose.yml
  - monitoring/docker-compose.yml
