{
 "title": "Vikunja",
 "description": "This is a Grafana Dashboard to show scraped metrics from Vikunja using Prometheus.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(vikunja_active_users, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vikunja Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Projects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vikunja_project_count{instance =~ \"$instance\"}",
     "legendFormat": "Project Count"
    }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vikunja_task_count{instance =~ \"$instance\"}",
     "legendFormat": "Task Count"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vikunja_active_users{instance =~ \"$instance\"}",
     "legendFormat": "User Count"
    }
   ]
  },
  {
   "title": "Active Link Shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vikunja_active_link_shares{instance =~ \"$instance\"}",
     "legendFormat": "Active Link Shares"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vikunja_user_count{instance =~ \"$instance\"}",
     "legendFormat": "Total User Count"
    }
   ]
  },
  {
   "title": "Total Teams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vikunja_team_count{instance =~ \"$instance\"}",
     "legendFormat": "Team Count"
    }
   ]
  },
  {
   "title": "Attachments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vikunja_attachments_count{instance =~ \"$instance\"}",
     "legendFormat": "Total Attachment Count"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vikunja_files_count{instance =~ \"$instance\"}",
     "legendFormat": "Total File Count"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mspan Inuse"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mspan Sys"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mcache Inuse"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mcache Sys"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buck Hash Sys"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "GC Sys"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\"} - go_memstats_other_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"}",
     "legendFormat": "Next GC"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "Inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"$instance\"}",
     "legendFormat": "Released"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "Stack Inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Stack Sys"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Memstats Sys"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Memstats Lookups Total"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Malloc Total"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\"} - go_memstats_frees_total{instance=~\"$instance\"}",
     "legendFormat": "Number of Live Objects"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Alloc"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "GC Duration {{ quantile }}s"
    }
   ]
  }
 ]
}