services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      WATCHTOWER_SCHEDULE: "0 0 5 * * *"
      WATCHTOWER_TIMEOUT: "60s"
      TZ: "America/New_York"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
